### PR TITLE
Add workflow

### PR DESCRIPTION
**Pull request by S-N00B-1**
Because teaching people to commit to GitHub, might be easier than getting them to install python.
It now compiles automagically.

### CODE REVIEW

**Comment by DBTDerpbox** [comment]
~~this probably wont be easy enough for coolguy to understand it still~~ thanks a lot for the help, but one thing is everything from windswept is included here

**Comment by DBTDerpbox** [comment]
even in the add workflow commit, there's a lot of windswept related stuff so i cant just do that one commit

should i just copy the workflow file and mark you as a contributor for it or you figure this out yourself?

**Comment by S-N00B-1** [comment]
Can’t make any new forks, so that’ll work.

**Comment by S-N00B-1** [comment]
This does depend on having that python file in the root directory.

**Comment by S-N00B-1** [comment]
I haven’t figured out a way around it yet, sorry.

**Comment by DBTDerpbox** [comment]
pretend i merged it, and i'm working on a fix for that

**Comment by DBTDerpbox** [comment]
yep i got it, made the action auto download the compiler every time

**Pull request closed without merging**
